version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  web:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      ADMIN_SECRET: change-me
      CSRF_SECRET: change-me
      CRON_SECRET: change-me
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - db
