name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Precompile templates
        run: npm run precompile-templates
      - name: Run tests
        run: npm test
      - name: Build app
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run e2e tests
        env:
          E2E_BASE_URL: http://localhost:3000
          E2E_COMMAND: npm run start
          ADMIN_SECRET: test_admin_secret
          REDIS_URL: redis://localhost:6379
        run: npm run e2e
      - name: Upload Playwright results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: |
            test-results/**
            playwright-report/**
          if-no-files-found: ignore
