name: Playwright E2E

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci
      - name: Generate Prisma client
        run: npx prisma generate
      - name: Prepare schema
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          if [ -n "${DATABASE_URL}" ]; then
            echo "DATABASE_URL present — running migrations"
            npx prisma migrate deploy
          else
            echo "No DATABASE_URL — using prisma db push for SQLite"
            npx prisma db push
          fi
      - name: Build
        run: npm run build
      - name: Start server (production)
        env:
          ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
          CSRF_SECRET: ${{ secrets.CSRF_SECRET }}
          NEXT_TELEMETRY_DISABLED: '1'
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          npm run start &
          # wait for health
          for i in {1..30}; do
            if curl -sS http://localhost:3000/api/health >/dev/null 2>&1; then echo ready; break; fi
            sleep 1
          done
      - name: Run Playwright tests
        env:
          ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
          CSRF_SECRET: ${{ secrets.CSRF_SECRET }}
          NEXT_TELEMETRY_DISABLED: '1'
          E2E_USE_DEV: '0'
          E2E_BASE_URL: 'http://localhost:3000'
          # Optional Stripe test secrets for billing tests; set in repo settings to enable billing e2e
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          PLAYWRIGHT_RUN_BILLING: ${{ secrets.PLAYWRIGHT_RUN_BILLING }}
        run: npx playwright test --reporter=list
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
