name: Scheduled CSP Purge

on:
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC
  workflow_dispatch: {}

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Call purge endpoint
        env:
          SITE_URL: ${{ secrets.SITE_URL }}
          ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          # Prefer SITE_URL + ADMIN_SECRET header; fall back to PURGE_URL+CRON_SECRET if configured
          if [ -n "$SITE_URL" ] && [ -n "$ADMIN_SECRET" ]; then
            echo "Calling $SITE_URL/api/admin/cron/purge-csp with admin secret"
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$SITE_URL/api/admin/cron/purge-csp" -H "x-admin-secret: $ADMIN_SECRET") || true
            echo "Purge endpoint returned $STATUS"
            exit 0
          fi
          if [ -n "$CRON_SECRET" ] && [ -n "$PURGE_URL" ]; then
            echo "Calling $PURGE_URL/api/cron/purge-csp with cron secret"
            curl -sS -X POST -H "Authorization: Bearer $CRON_SECRET" "$PURGE_URL/api/cron/purge-csp" | jq -r '.message // .' || true
            exit 0
          fi
          echo "No valid purge endpoint configuration found (SITE_URL+ADMIN_SECRET or PURGE_URL+CRON_SECRET). Skipping."
